created LaunchScreenActivity and inflated FrameLayout with Footer com…
SafetyHeads/Akademia-Androida-2023 pull request #10
Opened 2023-01-24 00:55 UTC by kapkus

created LaunchScreenActivity and inflated FrameLayout with Footer component

2023-01-24 08:06 UTC, przemek19980102 requested changes
Nie mogę uruchomić aplikacji, wykorzystałeś zdefiniowane kolory, które jeszcze nie zostały zmergowane do mastera. Jeżeli pobierze się repo z githuba jest ono niemożliwe do skompilowania, zrób proszę rebase na mastera (w prawym dolnym rogu z listy branchy wybierz master w sekcji "Remote" i kliknij "rebase task/12 onto remote/master" po tym jak zmiany odnośnie colors.xml realizowane w zadaniu numer 3 zostaną zmergowane :)

2023-01-27 08:18 UTC, przemek19980102 commented
group_12340.web should have a name suggesting what the picture is displaying or where it is used, for example `launcher_image.webp`

2023-01-29 19:04 UTC, przemek19980102 requested changes

2023-01-29 19:04 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +        android:layout_height="48dp"
Height of this button seems to be wrong when app is launched + it is purple instead of green

2023-01-29 19:04 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +        android:id="@+id/txt_sign"
Views in this layout should be constrained to start and end of the screen and have correct margin set

2023-01-29 19:04 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +        android:layout_marginTop="37dp"
please don't hardcode values in layouts, use values from dimens.xml if possible. Remember we use multipliers of 8dp so 37dp -> 40dp

2023-01-29 19:04 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +        android:layout_width="265dp"
Avoid hardcoded width in ConstraintLayout

2023-01-31 08:22 UTC, przemek19980102 requested changes

2023-01-31 08:22 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +        android:textSize="16sp"
Don't we have a style for TextView in styles.xml? Please also fix other TextViews in this xml file

2023-01-31 08:22 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +    <androidx.appcompat.widget.AppCompatButton
A standard <Button> wouldn't work?

2023-01-31 08:22 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
<img width="264" alt="image" src="https://user-images.githubusercontent.com/32803402/215705810-357fa045-43aa-4198-a089-1a30da64aca5.png">
Could you improve margins on the screen? It doesn't match the design, button should be glued to the footer

2023-01-31 08:22 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
in themes.xml you could also update android:statusBarColor to white so it matches the screen color

2023-02-02 21:41 UTC, przemek19980102 requested changes
really small change ;)

2023-02-02 21:41 UTC, przemek19980102 commented on app/src/main/res/layout/activity_launch_screen.xml
> +    android:layout_height="match_parent"
Looks great now, only missing background with n_0 color

2023-02-03 11:20 UTC, przemek19980102 approved these changes

2023-02-06 01:17 UTC, msarelo approved these changes

2023-02-06 01:17 UTC, merged