task/120 - FAQ Fragment
SafetyHeads/Akademia-Androida-2023 pull request #105
Opened 2023-05-17 13:27 UTC by Zalezny

2023-05-17 17:12 UTC, przemek19980102 requested changes
Please use strings.xml instead of directly typing the values in layouts. That's all for now but there are a few bugs

2023-05-17 17:12 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqViewModel.kt
> +    private val _typedFaqsList: MutableLiveData<List<Faq>?> = MutableLiveData<List<Faq>?>().apply {
List<Faq>? does it need to be nullable? We can always pass an empty list if there is no data

2023-05-17 17:12 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqViewModel.kt
> +    private fun getFaqs(type: Type) {
private methods should be placed below public ones in code, please move it to the bottom

2023-05-17 17:12 UTC, przemek19980102 commented on presentation/src/main/res/layout/dialog_ask_question.xml
> +        android:hint="Write your question"
this should be in strings/xml

2023-05-17 17:12 UTC, przemek19980102 commented on presentation/src/main/res/layout/faq_question_item.xml
> +        android:text="Lorem ipsum dolor sit amet"
This can be deleted I guess?

2023-05-17 17:12 UTC, przemek19980102 commented on presentation/src/main/res/layout/fragment_bottom_sheet_faq.xml
> +        android:text="OK"
@strings/ ?

2023-05-17 17:13 UTC, przemek19980102 commented
<img width="431" alt="image" src="https://github.com/SafetyHeads/Akademia-Androida-2023/assets/32803402/0485b728-af90-4dae-b71e-0d4b7e847f34">

2023-05-17 17:13 UTC, przemek19980102 commented
And I had a crash when clicked on submit button

FATAL EXCEPTION: main
                                                                                                    Process: com.safetyheads.akademiaandroida.development, PID: 2812
                                                                                                    java.lang.NullPointerException: isSuccess must not be null
                                                                                                    	at com.safetyheads.akademiaandroida.presentation.ui.fragments.faq.FaqFragment$askQuestionDialog$3.invoke(FaqFragment.kt:97)
                                                                                                    	at com.safetyheads.akademiaandroida.presentation.ui.fragments.faq.FaqFragment$askQuestionDialog$3.invoke(FaqFragment.kt:96)
                                                                                                    	at com.safetyheads.akademiaandroida.presentation.ui.fragments.faq.FaqFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7892)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

2023-05-18 19:58 UTC, msarelo requested changes

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqFragment.kt
> +        val dialogView = LayoutInflater.from(context).inflate(R.layout.dialog_ask_question, null)
This fragment should base on BottomSheetDialogFragment like ProfileBottomSheetDialogFragment

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqAdapter.kt
> +    override fun getItemCount(): Int {
You can be shorter:
```suggestion
    override fun getItemCount() = faqs.size
```

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqBottomSheetFragment.kt
> +    private lateinit var binding: FragmentBottomSheetFaqBinding
This field should be below companion object

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/res/layout/fragment_bottom_sheet_faq.xml
> +        android:id="@+id/btnOk"
Shadow of this button is cut a bit :
![image](https://github.com/SafetyHeads/Akademia-Androida-2023/assets/3758285/d1ebf6f5-2c19-4857-81cc-f9406560f249)

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqViewModel.kt
> +                                _typedFaqsList.postValue(typedFaqs)
`typedFaqs` should be posted after iteration.

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/faq/FaqViewModel.kt
> +                                _typedFaqsList.postValue(typedFaqs)
In Kotlin you can do that in much shorter form:
```suggestion
                if (result.isSuccess) {
                    val faqsList = result.getOrNull()
                        ?.filter { it.type == type.type && it.publish }.orEmpty()
                    _typedFaqsList.postValue(faqsList)
                }
```

2023-05-18 19:58 UTC, msarelo commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/wearehiring/WeAreHiringFragment.kt
> +        binding.applyNow.setOnClickListener { }
I suggest to leave a comment with TODO

2023-05-20 18:01 UTC, msarelo approved these changes

2023-05-20 18:01 UTC, merged