task/136 - Przenieść ekrany z modułu app do presentation
SafetyHeads/Akademia-Androida-2023 pull request #107
Opened 2023-05-17 19:25 UTC by jordanrafalm

2023-05-18 20:05 UTC, przemek19980102 requested changes

2023-05-18 20:05 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/youtubefragments/PlayListViewModel.kt
> +package com.safetyheads.akademiaandroida.presentation.ui.fragments.youtubefragments
youtubefragments package name seems off. It could be just "youtube"

2023-05-18 20:05 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/youtubefragments/diffUtil/VideoDiffUtil.kt
> +package com.safetyheads.akademiaandroida.presentation.ui.fragments.youtubefragments.diffUtil
why files in diffUtil aren't in the same package as rest of youtube related classes?

2023-05-18 20:15 UTC, msarelo submitted a review, later dismissed

2023-05-23 07:28 UTC, przemek19980102 approved these changes

2023-05-23 09:33 UTC, Kuba-Nalepa submitted a review, later dismissed

2023-05-23 19:15 UTC, merged