Task/147 - better navigation
SafetyHeads/Akademia-Androida-2023 pull request #120
Opened 2023-06-01 19:55 UTC by Zalezny

2023-06-04 18:08 UTC, Kuba-Nalepa approved these changes

2023-06-06 09:44 UTC, przemek19980102 requested changes

2023-06-06 09:44 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/MainActivity.kt
> +    private fun observers() {
previous name was a little bit more meaningful, please revert it

2023-06-06 09:44 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/activities/DashboardActivity.kt
> +                    "com.safetyheads.akademiaandroida.presentation.ui.MainActivity"
Why do we have to start activity by it's name? Can't we just do a regular intent with MainActivity.class?

2023-06-06 09:44 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/viewmodels/DashboardViewModel.kt
>      val isExistUser: LiveData<Boolean> = _isExistUser
shouldn't this be `doesUserExist` ?

2023-06-13 08:13 UTC, przemek19980102 approved these changes

2023-06-14 10:12 UTC, merged