Task 149 - Navigation from unlogged dashboard to MainActivity
SafetyHeads/Akademia-Androida-2023 pull request #121
Opened 2023-06-01 22:29 UTC by Kuba-Nalepa

Moreover I did little fixes in login/registration/forgot password layouts like correcting them properly using custom views, changing overlapped text views, setting (working) navigation buttons

2023-06-04 06:41 UTC, Zalezny requested changes
Big plus for adding the back arrow component and cleaning up in the code app. As for the task itself, everything seems ok, just a few code fixes needed

2023-06-04 06:41 UTC, Zalezny commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/activities/DashboardActivity.kt
> +import android.util.Log
unused import

2023-06-04 06:41 UTC, Zalezny commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/activities/DashboardActivity.kt
> +import com.safetyheads.akademiaandroida.presentation.ui.customviews.DashboardFragment
unused import

2023-06-04 06:41 UTC, Zalezny commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/components/BackArrowView.kt
> +//        binding.imageButton.setOnClickListener()
unused comment

2023-06-04 06:41 UTC, Zalezny commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/customviews/DashboardFragment.kt
> +                    startActivity(intent)
Please add "finish()" these activity. I think that "finish()" in MainActivity (when open DashboardActivity) will fix the error when we come from Sign in and return next

2023-06-05 07:11 UTC, Zalezny submitted a review, later dismissed

2023-06-06 10:14 UTC, przemek19980102 requested changes

2023-06-06 10:14 UTC, przemek19980102 commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/signup/SignUpFragment.kt
> +            findNavController().navigateUp()
are you sure we should do the same action as for back button?

2023-06-06 10:14 UTC, przemek19980102 commented on presentation/src/main/res/layout/fragment_faq.xml
> +                android:id="@+id/textView4"
this is not really a good name for an id

2023-06-06 10:14 UTC, przemek19980102 commented on presentation/src/main/res/layout/fragment_faq.xml
> +            android:id="@+id/h2View3"
this is not really a good name for an id

2023-06-06 10:14 UTC, przemek19980102 commented on presentation/src/main/res/layout/fragment_forgot_password.xml
> +            android:layout_width="128dp"
can't we make those 0dp and somehow align it in the layout so it looks good and it is not hardcoded?

2023-06-07 07:35 UTC, przemek19980102 approved these changes

2023-06-07 09:28 UTC, merged