Created Services screen + little fixes in styles
SafetyHeads/Akademia-Androida-2023 pull request #124
Opened 2023-06-04 18:05 UTC by Kuba-Nalepa

2023-06-05 13:18 UTC, Zalezny commented on presentation/src/main/res/layout/fragment_services.xml
> +        android:layout_marginTop="20dp"
dimens can be here

2023-06-05 13:18 UTC, Zalezny commented on presentation/src/main/java/com/safetyheads/akademiaandroida/presentation/ui/fragments/services/ServicesFragment.kt
> +                //
I think better is //no-op

2023-06-05 19:27 UTC, Zalezny submitted a review, later dismissed
seems ok

2023-06-06 10:26 UTC, forceindia712 requested changes

2023-06-06 10:26 UTC, forceindia712 commented on presentation/src/main/res/layout/fragment_services.xml
> +        app:text="Services"
I recommend putting "Services" into strings.xml

2023-06-06 12:35 UTC, forceindia712 approved these changes

2023-06-06 12:52 UTC, Zalezny approved these changes

2023-06-06 12:55 UTC, merged