Task 14 - Created (Company) TabLayout style
SafetyHeads/Akademia-Androida-2023 pull request #14
Opened 2023-01-24 21:13 UTC by Kuba-Nalepa

2023-01-25 17:13 UTC, msarelo requested changes
Please resolve conflicts

2023-01-25 22:43 UTC, msarelo commented
Please resolve conflicts again :)

2023-01-26 08:13 UTC, przemek19980102 submitted a review, later dismissed
Looks good. Resolve conflicts and we can merge

2023-01-29 18:50 UTC, przemek19980102 approved these changes

2023-01-29 23:28 UTC, msarelo approved these changes

2023-01-29 23:28 UTC, merged