Task/13 Created title component
SafetyHeads/Akademia-Androida-2023 pull request #15
Opened 2023-01-25 16:13 UTC by Zalezny

2023-01-25 23:42 UTC, msarelo commented
The implementation is good. But let's try to do that in simpler way. Please try to use only style :), hints:
- drawableStart
- drawablePadding
- you can set size (<size></size>) inside shape

 or just extends in H2View AppCompatTextView and ImageView on the left side of text.

2023-01-27 08:48 UTC, przemek19980102 requested changes
Some small changes but otherwise looks ok :)

2023-01-27 08:48 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/H2View.kt
> +
Remove empty lines here

2023-01-27 08:48 UTC, przemek19980102 commented on app/src/main/res/drawable/line_2422.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android"
Name of the file should be better, for example h2_view_line

2023-01-27 08:48 UTC, przemek19980102 commented on app/src/main/res/layout/h2_view.xml
> +<merge xmlns:android="http://schemas.android.com/apk/res/android"
please rename it to view_h2

2023-01-29 18:49 UTC, przemek19980102 approved these changes

2023-01-29 23:31 UTC, merged