Task/27 - Connecting social media to Contact with us fragment
SafetyHeads/Akademia-Androida-2023 pull request #24
Opened 2023-01-31 16:39 UTC by forceindia712

Nie działa otwieranie facebooka

2023-02-02 07:11 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/contact_with_us/ContactWithUsFragment.kt
> +    companion object {
please move companion object to the top of the class

2023-02-02 07:13 UTC, przemek19980102 commented on app/src/main/res/values/strings.xml
> +    <string name="install_app">Czy chcesz zainstalować aplikację</string>
english :)

2023-02-03 00:42 UTC, forceindia712 commented
Poprawki wprowadzone, facebook działa :)

2023-02-06 02:02 UTC, msarelo requested changes

2023-02-06 02:02 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/contact_with_us/ContactWithUsFragment.kt
> +        val YouTube = "YouTube"
Enum or seald class will be more sutable here and then you could reduce amount of code lines in this class.

2023-02-07 07:04 UTC, przemek19980102 approved these changes

2023-02-07 12:04 UTC, przemek19980102 submitted a review, later dismissed

2023-02-11 15:20 UTC, msarelo approved these changes
Super robota 👍 

Rozwiąż konflikty i będziemy mergować

2023-02-12 08:16 UTC, przemek19980102 approved these changes

2023-02-14 20:46 UTC, przemek19980102 approved these changes

2023-02-14 22:59 UTC, merged