Task/28 - Validator of full name
SafetyHeads/Akademia-Androida-2023 pull request #26
Opened 2023-02-01 11:45 UTC by Zalezny

2023-02-02 07:01 UTC, przemek19980102 requested changes
Some minor changes here. Could you also provide a description on how to test the change?

2023-02-02 07:01 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/utils/FullNameVaildator.kt
> +
remove empty line

2023-02-02 21:38 UTC, przemek19980102 requested changes

2023-02-02 21:38 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/utils/FullNameVaildator.kt
> +    private const val maxTextLength = 10
It should be 100, not 10

2023-02-02 21:38 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/utils/FullNameVaildator.kt
> +object FullNameValidator {
Something is not right, when I type "ABC" then it returns that surname is ok even if there is no surname

2023-02-03 11:22 UTC, przemek19980102 approved these changes

2023-02-06 01:27 UTC, msarelo submitted a review, later dismissed

2023-02-07 07:03 UTC, przemek19980102 approved these changes

2023-02-12 16:12 UTC, msarelo approved these changes

2023-02-12 16:42 UTC, merged