Task 22 - Create Experience Structure Section
SafetyHeads/Akademia-Androida-2023 pull request #29
Opened 2023-02-02 16:32 UTC by Kuba-Nalepa

2023-02-02 21:26 UTC, przemek19980102 requested changes
After you fix issues mentioned in taks number 20 please rebase this branch on the 20 so you can use style from there

2023-02-02 21:26 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_experience_structure.xml
> +    app:cardUseCompatPadding="true">
This prevents the card from filling the screen horizontally, please remove :)

2023-02-06 01:36 UTC, msarelo submitted a review, later dismissed

2023-02-08 15:04 UTC, przemek19980102 approved these changes

2023-02-09 15:40 UTC, merged