Task 9 - Create style for button
SafetyHeads/Akademia-Androida-2023 pull request #33
Opened 2023-02-06 03:27 UTC by infitex24

On Zepplin is comment to create a simple animation when button is pressed. I dont know how to implement that.

2023-02-07 06:58 UTC, przemek19980102 requested changes

2023-02-07 06:58 UTC, przemek19980102 commented on app/src/main/res/values/styles.xml
> +        <item name="android:width">312dp</item>
width should be set to match_parent

2023-02-07 06:58 UTC, przemek19980102 commented on app/src/main/res/values/styles.xml
> +        <item name="android:width">312dp</item>
to add the effect you were mentioning: android:foreground="?selectableItemBackground" or ?selectableItemBackgroundBorderless, check which one looks better

2023-02-11 14:20 UTC, msarelo requested changes
Co do animacji zobacz co tutaj radzą:
https://stackoverflow.com/questions/40008609/add-ripple-effect-to-my-button-with-button-background-color

Dodaj przykładowy ekran z użyciem takiego przycisku.

2023-02-16 16:23 UTC, msarelo requested changes
Rozwiąż konflikty. PR powinien zawierać tylko Twoje zmiany. Zobacz na diffa, są tutaj zmiany z innych branczy.

2023-02-20 14:59 UTC, przemek19980102 requested changes

2023-02-20 14:59 UTC, przemek19980102 commented on app/src/main/res/values/styles.xml
> +        <item name="android:background">@drawable/button_style</item>
Rename button_style image to button_background

2023-02-20 14:59 UTC, przemek19980102 commented on app/src/main/res/values/styles.xml
> +    <style name="Button_style" parent="@android:style/TextAppearance.Small">
name of the style shouldn't have capital letters

2023-02-28 16:40 UTC, msarelo requested changes

2023-02-28 16:40 UTC, msarelo commented on app/src/main/res/values/styles.xml
> +    <style name="button_background" parent="@android:style/TextAppearance.Small">
Nazwa stylu nie oddaje co faktycznie ten styl modyfikuje. Nazwał bym raczej coś w stylu: `StyledButton`

2023-03-02 12:01 UTC, msarelo approved these changes

2023-03-02 12:01 UTC, merged