Task/36 - create navigation component
SafetyHeads/Akademia-Androida-2023 pull request #34
Opened 2023-02-06 20:07 UTC by magda2307

2023-02-07 07:28 UTC, przemek19980102 requested changes

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/dashboard_placeholder.kt
> +    private var param1: String? = null
you can totally remove the param1 and param2 thing

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/dashboard_placeholder.kt
> +        fun newInstance(param1: String, param2: String) =
this approach is very good, however please remove params

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/dashboard_placeholder.kt
> +// TODO: Rename parameter arguments, choose names that match
remove unnecessary comments after you remove the params

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/dashboard_placeholder.kt
> +class dashboard_placeholder : Fragment() {
class name should be DashboardPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/login_placeholder.kt
> +class login_placeholder : Fragment() {
LoginPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/login_placeholder.kt
> +private const val ARG_PARAM1 = "param1"
the same comments as in DashboardPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/mainscreen_placeholder.kt
> +// TODO: Rename parameter arguments, choose names that match
the same comments as in DashboardPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/mainscreen_placeholder.kt
> +class mainscreen_placeholder : Fragment() {
MainScreenPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/notlogged_placeholder.kt
> +private const val ARG_PARAM1 = "param1"
The same comments as in DashboardPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/notlogged_placeholder.kt
> +class notlogged_placeholder : Fragment() {
NotLoggedPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/splash_placeholder.kt
> +class splash_placeholder : Fragment() {
SplashPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/splash_placeholder.kt
> +private const val ARG_PARAM1 = "param1"
the same comments as in DashboardPlaceholder

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/login_placeholder.kt
> +            Navigation.findNavController(view).navigate(R.id.dashboard_placeholder)
R.id.action_login_placeholder_to_dashboard_placeholder should be used instead 🤔 
this applies to all ...navigate() calls you have

2023-02-07 07:28 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/login_placeholder.kt
> +            Navigation.findNavController(view).navigate(R.id.dashboard_placeholder)
use actions that are in XML instead of calling fragments directly

2023-02-07 17:14 UTC, przemek19980102 requested changes

2023-02-07 17:14 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/RootActivity.kt
> +                if (navController.currentDestination?.id == R.id.mainscreen_placeholder || navController.currentDestination?.id == R.id.dashboard_placeholder) {
zerknij proszę na https://stackoverflow.com/a/59426267 czy da się w XMLu zastąpić tego OnBackPressedCallback?

2023-02-09 16:03 UTC, przemek19980102 submitted a review, later dismissed

2023-02-11 19:50 UTC, msarelo commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".RootActivity"
Zamiast zmieniać startową aktywność, dodaj przycisk który odpali ten fragment z MainActivity

2023-02-11 19:52 UTC, msarelo requested changes
Rozwiąż konflikty

2023-02-14 23:22 UTC, merged