Task/24
SafetyHeads/Akademia-Androida-2023 pull request #35
Opened 2023-02-06 22:21 UTC by jordanrafalm

2023-02-07 07:11 UTC, przemek19980102 requested changes

2023-02-07 07:11 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_clients.xml
> +    android:layout_width="360dp"
match_parent

2023-02-07 07:11 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_clients.xml
> +    android:layout_height="263dp"
match_parent

2023-02-07 07:11 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_clients.xml
> +        android:layout_marginStart="208dp"
do not hardcode margins, in this task you could delete most of them, take a look at:
https://medium.com/@nomanr/constraintlayout-chains-4f3b58ea15bb

2023-02-09 12:55 UTC, przemek19980102 requested changes

2023-02-09 12:55 UTC, przemek19980102 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_7.5x">60dp</dimen>
woah... please remove all those, we don't need that many, we aren't probably using even half of that!

2023-02-09 12:55 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_clients.xml
> +        android:layout_marginStart="@dimen/margin_37x"
Try to implement this layout using as few margins as possible, this is way too many

2023-02-11 14:39 UTC, msarelo requested changes
- W PR powinny być tylko Twoje zmiany.
- Spróbuj zaimportować pliki SVG zamiast PNG
- Marginesy powinny dopasowywane względem elementów - tak jak wyjaśniłem ostatnio na spotkaniu.

2023-02-16 16:43 UTC, merged