Task/30 Create EmailValidator
SafetyHeads/Akademia-Androida-2023 pull request #46
Opened 2023-02-21 12:00 UTC by rafalkrystek

2023-02-23 14:59 UTC, przemek19980102 requested changes
Please rebase onto master and take a look at PhoneNumberValidator. Your class should have similar methods

2023-02-26 01:52 UTC, msarelo requested changes

2023-02-26 01:52 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/utils/EmailValidator.java
> +        if (!emailToText.isEmpty() && Patterns.EMAIL_ADDRESS.matcher(emailToText).matches()) {
It's not something we can reuse in other parts in the app.

2023-03-08 12:02 UTC, przemek19980102 requested changes

2023-03-08 12:02 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_launch_screen.xml
> +        style="@style/Button"
Are you sure those changes should be in this PR?

2023-03-08 12:02 UTC, przemek19980102 commented on app/src/main/res/layout/fragment_we_are_hiring.xml
> +        style="@style/Button"
Are you sure those changes should be in this PR?

2023-03-14 17:34 UTC, msarelo approved these changes

2023-03-14 18:10 UTC, przemek19980102 approved these changes

2023-03-14 18:11 UTC, merged