Task/54 - Unit test for name and surname
SafetyHeads/Akademia-Androida-2023 pull request #48
Opened 2023-02-24 21:53 UTC by forceindia712

Nie jestem pewien czy ostatni test jest dobrze wykonany.

2023-02-25 08:53 UTC, przemek19980102 submitted a review, later dismissed

2023-02-26 02:03 UTC, msarelo requested changes

2023-02-26 02:03 UTC, msarelo commented on app/src/test/java/com/safetyheads/akademiaandroida/FullNameVaildatorTest.kt
> +        val result = FullNameValidator.validateName(name, splitNames, editText, context)
Why editText and context is necessary in`validateName`for validated.

2023-02-28 17:02 UTC, msarelo commented on app/src/test/java/com/safetyheads/akademiaandroida/FullNameVaildatorTest.kt
> +        val result = FullNameValidator.validateName(name, splitNames, editText, context)
Nvm, it isn't scope of this PR.

2023-03-02 11:58 UTC, msarelo approved these changes

2023-03-02 11:58 UTC, merged