Task/61
SafetyHeads/Akademia-Androida-2023 pull request #63
Opened 2023-03-16 15:44 UTC by infitex24

2023-03-27 19:42 UTC, Kuba-Nalepa reviewed
Registration view looks good :)
Please create ViewModel, UseCase, and UserRepository
P.s Have You checked if validator correctly displays the error?

2023-04-06 14:37 UTC, msarelo requested changes

2023-04-06 14:37 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/sign_up/SignUpViewModel.kt
> +    fun signUp(eTextFullName: TextInputEditText, eTextEmailAddress: TextInputEditText, eTextPassword: TextInputEditText, eTextConfirmPassword: TextInputEditText) {
`signUp` function parameters should be `String` rather than `TextInputEditText`.

2023-04-10 11:33 UTC, msarelo requested changes

2023-04-10 11:33 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/sign_up/UserRepositoryImpl.kt
> +class UserRepositoryImpl {
```suggestion
class UserRepositoryImpl : UserRepository {
```

2023-04-16 00:04 UTC, msarelo approved these changes

2023-04-16 16:27 UTC, Kuba-Nalepa approved these changes

2023-04-16 17:01 UTC, merged