Task 95 - Created domain module, added entity, repository, usecase packages to it
SafetyHeads/Akademia-Androida-2023 pull request #68
Opened 2023-03-23 21:55 UTC by Kuba-Nalepa

2023-03-28 18:10 UTC, msarelo requested changes

2023-03-28 18:10 UTC, msarelo commented on domain/build.gradle
> +    id 'com.android.library'
This module should be pure java/kotlin library.

2023-03-30 11:44 UTC, msarelo approved these changes

2023-03-30 12:21 UTC, jordanrafalm approved these changes

2023-03-30 12:50 UTC, merged