task/98 - create module presentation
SafetyHeads/Akademia-Androida-2023 pull request #80
Opened 2023-04-11 14:37 UTC by jordanrafalm

2023-04-16 17:32 UTC, msarelo requested changes
- Test should be also moved
- Main application and navigation also should be in the app module

2023-04-16 17:32 UTC, msarelo commented on app/src/main/java/com/safetyheads/presentation/utils/AndroidAcademyApplication.kt
> -package com.safetyheads.akademiaandroida
`AndroidAcademyApplication` should stay in app module.

2023-04-16 17:36 UTC, msarelo requested changes

2023-04-16 17:36 UTC, msarelo commented on presentation/src/main/AndroidManifest.xml
> +    <application
it should stay in app module, we don't need <application/> in module

2023-04-16 17:36 UTC, msarelo commented on presentation/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
launcher should be in the app module

2023-04-16 17:36 UTC, msarelo commented on presentation/src/main/res/values-night/themes.xml
> +    <!-- Base application theme. -->
it also should be in the app module

2023-04-19 11:35 UTC, forceindia712 submitted a review, later dismissed

2023-04-25 15:29 UTC, closed without merging