Task/96 - Adding the main module
SafetyHeads/Akademia-Androida-2023 pull request #81
Opened 2023-04-12 11:01 UTC by forceindia712

BuildConfig and Log not working

2023-04-16 17:39 UTC, msarelo requested changes

2023-04-16 17:39 UTC, msarelo commented on data/src/main/java/com/safetyheads/data/objects/YouTubeApi.kt
> +package com.safetyheads.data.objects
```suggestion
package com.safetyheads.data.network
```

2023-04-16 17:39 UTC, msarelo commented on data/src/main/java/com/safetyheads/data/repository/NetworkRepository.kt
> +package com.safetyheads.data.repository
```suggestion
package com.safetyheads.data.network.repository
```

2023-04-16 17:39 UTC, msarelo commented on data/src/main/java/com/safetyheads/data/retrofit/ApiClient.kt
> +package com.safetyheads.data.retrofit
```suggestion
package com.safetyheads.data.network.retrofit
```

2023-04-16 17:39 UTC, msarelo commented on data/src/main/java/com/safetyheads/data/services/YouTubeService.kt
> +package com.safetyheads.data.services
```suggestion
package com.safetyheads.data.network.services
```

2023-04-16 17:39 UTC, msarelo commented on data/src/test/java/com/safetyheads/domain/ExampleUnitTest.kt
> +package com.safetyheads.domain
```suggestion
package com.safetyheads.data
```

2023-04-24 10:10 UTC, rafalkrystek reviewed
Check code formatting for example in here: 
                    Log.d(tag, message)
                }
// (empty line)
            }
            
            
class ApiClient(private val isDebug:Boolean, private val appLogger: AppLogger) {
// (missing space)

Use CTRL + ALT + L and CTRL + ALT + O

2023-04-24 10:10 UTC, rafalkrystek commented on data/src/androidTest/java/com/safetyheads/data/ExampleInstrumentedTest.kt
Is this necessary? looks like android studio added test by default

2023-04-24 10:10 UTC, rafalkrystek commented on data/src/test/java/com/safetyheads/data/ExampleUnitTest.kt
Is this necessary? Looks like android studio added test by default.

2023-04-24 10:50 UTC, przemek19980102 requested changes

2023-04-24 10:50 UTC, przemek19980102 commented on data/src/main/java/com/safetyheads/data/network/services/YouTubeService.kt
> +interface YouTubeService {
is this expected to be empty?

2023-04-24 10:50 UTC, przemek19980102 commented on data/src/main/java/com/safetyheads/data/network/retrofit/RetrofitInterceptor.kt
> +    override fun intercept(chain: Interceptor.Chain): Response {
do we need it? as well as AppLogger? There is a library for that already https://stackoverflow.com/a/33256827

2023-04-24 12:24 UTC, forceindia712 commented on data/src/androidTest/java/com/safetyheads/data/ExampleInstrumentedTest.kt
When creating modules, classes for tests create themselves.

2023-04-25 10:40 UTC, przemek19980102 reviewed
Fixes to my comments are looking good

2023-04-25 17:11 UTC, msarelo approved these changes

2023-04-25 17:12 UTC, merged