Task/34 - forgot password
SafetyHeads/Akademia-Androida-2023 pull request #83
Opened 2023-04-13 18:13 UTC by Zalezny

![image](https://user-images.githubusercontent.com/65240240/231846729-b3d84bcf-555f-4a72-99a3-d9870c8c7f28.png)

Check send email result:

https://user-images.githubusercontent.com/65240240/231847449-190c74f1-d840-40d2-abaa-8025000e38a1.mp4

2023-04-16 10:45 UTC, msarelo requested changes

2023-04-16 10:45 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/forgotpasswordfragment/ForgotPasswordFragment.kt
> +            forgotPasswordViewModel.setError(etEmail.error?.toString() ?: "")
```suggestion
            forgotPasswordViewModel.setError(etEmail.error?.toString().orEmpty())
```

2023-04-16 10:45 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/forgotpasswordfragment/ForgotPasswordFragment.kt
> +            }
```suggestion
            if (errorMsg.isNullOrEmpty()) {
                requestBtn.backgroundTintList = getColor(R.color.p_60)
            } else {
                requestBtn.backgroundTintList = getColor(R.color.p_30)
            }
```

2023-04-16 10:45 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/forgotpasswordfragment/ForgotPasswordFragment.kt
> +                TODO("Success of sent reset Password on email")
Please add Snackbar as at this screen:
https://zpl.io/XYo0LxK

2023-04-16 10:45 UTC, msarelo commented on app/src/main/java/com/safetyheads/akademiaandroida/forgotpasswordfragment/ForgotPasswordViewModel.kt
> +                }
```suggestion
                    _isSuccess.postValue(result.isSuccess)
                }
```

2023-04-16 10:45 UTC, msarelo commented on app/src/main/res/layout/fragment_forgot_password.xml
> +
```suggestion
```

2023-04-16 10:45 UTC, msarelo commented on app/src/main/res/layout/fragment_forgot_password.xml
> +
```suggestion
```

2023-04-16 10:45 UTC, msarelo commented on app/src/main/res/layout/fragment_forgot_password.xml
> +
```suggestion
```

2023-04-16 10:45 UTC, msarelo commented on domain/build.gradle
> +
```suggestion
```

2023-04-16 10:45 UTC, msarelo commented on domain/src/main/java/com/safetyheads/domain/usecases/ResetPasswordUseCase.kt
> +    class ResetParam(val email: String) : BaseUseCase.Params
```suggestion
    value class ResetParam(val email: String) : BaseUseCase.Params
```

2023-04-16 10:45 UTC, msarelo commented on domain/src/main/java/com/safetyheads/domain/usecases/ResetPasswordUseCase.kt
> +                        emit(Result.failure(resetPasswordEntity.error ?: Exception()))
```suggestion
                        emit(Result.failure(resetPasswordEntity.error ?: Exception("Reset password failed")))
```

2023-04-16 10:45 UTC, msarelo commented on domain/src/main/java/com/safetyheads/domain/usecases/ResetPasswordUseCase.kt
> +            } catch (error: java.lang.Exception) {
```suggestion
            } catch (error: Exception) {
```

2023-04-17 13:56 UTC, Zalezny commented
Snackbar with navigation and safeargs (it's only work on root activity):

https://user-images.githubusercontent.com/65240240/232505668-8bff7cf1-8ed7-45bb-b8d1-27be2609d743.mp4

2023-04-20 20:14 UTC, msarelo requested changes

2023-04-20 21:54 UTC, Zalezny commented on app/src/main/java/com/safetyheads/akademiaandroida/forgotpasswordfragment/snackbar/View.kt
> +internal fun View?.findSuitableParent(): ViewGroup? {
I'm not sure that is in android-ktx. I can't even find findSuitableParent() in official docs about androidx view. When I removed it from the project, nothing was found. It is just in Snackbar.java implemented:

![image](https://user-images.githubusercontent.com/65240240/233494095-2cc8264b-e1a4-4e04-a651-fd5ab286af12.png)

I checked it on Github and they paste this code into their projects every time:

https://github.com/search?l=Kotlin&o=desc&q=findSuitableParent&s=indexed&type=Code

2023-04-23 15:26 UTC, merged