Task/87 - Adding dashboard
SafetyHeads/Akademia-Androida-2023 pull request #86
Opened 2023-04-17 19:18 UTC by infitex24

Task 87 - I added basic dashboard. I'm still wondering if I should use a selector to change the background of the "button" (cause its not button, i did it like user click on "LinearLayout because its all space [icon and text below]" or if it should be handled in logic just setting backgrounds i added "dashboard_round_background_active" and "...non_active"?

2023-04-18 18:00 UTC, przemek19980102 requested changes

2023-04-18 18:00 UTC, przemek19980102 commented on app/src/main/java/com/safetyheads/akademiaandroida/DashboardFragment.kt
> +class DashboardFragment : Fragment() {
clicking on the bottom icons doesn't work (doesn't even change selection)

2023-04-19 20:25 UTC, msarelo requested changes

2023-04-19 20:25 UTC, msarelo commented on app/src/main/res/layout/fragment_dashboard.xml
> +        <LinearLayout
Hmm did you tried https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView?
Implementation details:
https://m2.material.io/components/bottom-navigation/android#using-bottom-navigation
or
https://github.com/material-components/material-components-android/blob/master/docs/components/BottomAppBar.md

2023-05-16 15:03 UTC, closed without merging